### ISSUE TITLE
configure error

### ISSUE THREAD

**Issue by 11111000000** [emallson/gram#16]
./configure: line 4157: syntax error near unexpected token `GUILE,'
./configure: line 4157: `PKG_CHECK_MODULES(GUILE, guile-2.0)'

**Comment by emallson** [comment]
Hi! This project is no longer being worked on actively, so I'm not sure that I'll ever get an answer to you.

However, this looks like an issue with `autotools` versions. Running `./configure` on Debian stable is completing correctly and everything compiles.

**Comment by rekado** [comment]
This error could mean that the Guile development package is not installed.

**Comment by 11111000000** [comment]
NixOs

**Comment by emallson** [comment]
NixOS is its own beast and doesn't interact nicely with any existing packaging infrastructure. You will at a minimum need to build an env with the `guile` and `autoconf`  packages, and possibly others. Many build systems require custom patches to work in a nix environment, and I would not be surprised if gram does as well.
