### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Schroedinger50PCT** [emallson/gram#17]
I am currently writing a package definition to build gram with the guix package manager. It would be helpful to know under what license terms the package can be released in case it should build one day.

**Comment by emallson** [comment]
I would recommend against packaging this for general consumption as it is incomplete and basically abandoned.

Regardless, the license is BSD 3-clause. I'll add a license later today.

**Comment by Schroedinger50PCT** [comment]
Oh, don't worry, the package exists mainly just to make it easier to play around with your wm on my guix system. I had already built it from git and loosely wired it up. It looked somewhat nice but I didn't plan to release the package in an official channel right away. The License field of my package template just made me think about it.
